// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'aiImage': string;
  'successfulFlowCreationPage': string;
  'textSummary': string;
}
export const cssExports: CssExports;
export default cssExports;
